export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE'

export const CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST'
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS'
export const CONFIRM_OTP_FAILURE = 'CONFIRM_OTP_FAILURE'