export const TOGGLE_MODAL_REQUEST = 'TOGGLE_MODAL_REQUEST';
export const TOGGLE_TRANSLATED_LANGUAGE = 'TOGGLE_TRANSLATED_LANGUAGE';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const CLEAR_CURRENT_INDEX = 'CLEAR_CURRENT_INDEX';
